server:
  port: 8081

spring:
  application:
    name: email-service

  datasource:
    url: jdbc:postgresql://localhost:5432/email_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "seu-email@gmail.com"
    password: "sua-senha"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: localhost
    port: 5672
